#spring:
  #datasource:
    #url: jdbc:postgresql://34.147.225.91:5432/NYSeeNow
    #username: Group13
    #password: 13NYSeeNow13
    #driver-class-name: org.postgresql.Driver
  #jpa:
    #database: POSTGRESQL
    #database-platform: org.hibernate.dialect.PostgreSQLDialect
    #hibernate:
      #ddl-auto: update
    #show-sql: true
    #properties:
      #hibernate:
        #format_sql: true
        #use_sql_comments: true
        #default_schema: busyness





spring:
  datasource:
    url: jdbc:postgresql://nyseenow.cbqpbir87k5q.eu-west-1.rds.amazonaws.com:5432/UserAccount
    username: fei
    password: 22200125
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  mvc:
    content-negotiation:
      favor-parameter: true
logging:
  level:
    org.springframework: DEBUG
